#Define the goal

uint8 DRIVE_TASK   = 0
uint8 REVERSE_TASK = 1
uint8 task

uint8 POSE_TYPE = 1     #expect server plan a path to reach the goal pose
uint8 PATH_TYPE = 2     #path points
uint8 FILE_TYPE = 3     #a path file name
uint8 type

geometry_msgs/Pose2D   target_pose  #POSE_TYPE
geometry_msgs/Pose2D[] target_path  #PATH_TYPE
string  roadnet_file                #FILE_TYPE
bool    path_filp

bool    cycle_run         #weather let robot running along a cycle road?

float32 path_resolution
float32 expect_speed

---
#Define the result
bool success
---

#Define a feedback message
float32 speed       #km/h
float32 steer_angle #deg ccw(-) cw(+)
float32 percentage
